# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-26 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=100)),
                ('race', models.CharField(choices=[('Z', 'Zerg'), ('T', 'Terran'), ('P', 'Protoss'), ('R', 'Random')], max_length=1)),
                ('rating', models.IntegerField(default=1200)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('match_map', models.CharField(choices=[('FS', 'Fighting Spirit'), ('CB', 'Circuit Breaker')], max_length=3)),
                ('rated', models.BooleanField(default=True)),
                ('replay', models.FileField(upload_to='')),
            ],
        ),
    ]
