# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-26 18:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ladder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='handle',
        ),
        migrations.AddField(
            model_name='match',
            name='loser',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='loss', to='ladder.Player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='loser_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='win', to='ladder.Player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='winner_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='battlenet',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='discord',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='iccup',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='shield_battery',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
