# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-26 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0004_auto_20170526_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='loser_rating_change',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='winner_rating_change',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
