# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-27 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0005_auto_20170526_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='loser_rating_change',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner_rating_change',
            field=models.IntegerField(null=True),
        ),
    ]
