# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-27 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0006_auto_20170527_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='replay',
            field=models.FileField(upload_to='replays'),
        ),
    ]
