# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-28 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0007_auto_20170527_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_map',
            field=models.CharField(choices=[('FS', 'Fighting Spirit'), ('CB', 'Circuit Breaker'), ('DE', 'Destination'), ('JA', 'Jade'), ('QB', 'Queensbridge')], max_length=3, verbose_name='Map'),
        ),
    ]
