# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-29 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0009_auto_20170528_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
