# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 01:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ladder', '0011_auto_20170530_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('time_reported', models.DateTimeField(auto_now_add=True)),
                ('report_type', models.CharField(choices=[('FRAUD', 'Fraudulent Match'), ('BM', 'BM/Misconduct'), ('DUP', 'Duplicate Match'), ('INC', 'Incorrect Data')], max_length=10)),
                ('resolved', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladder.Match')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
