# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 19:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0012_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='rated',
        ),
        migrations.AddField(
            model_name='match',
            name='loser_race',
            field=models.CharField(blank=True, choices=[('Z', 'Zerg'), ('T', 'Terran'), ('P', 'Protoss'), ('R', 'Random')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='winner_race',
            field=models.CharField(blank=True, choices=[('Z', 'Zerg'), ('T', 'Terran'), ('P', 'Protoss'), ('R', 'Random')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='loser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_map',
            field=models.CharField(blank=True, choices=[('AN', 'Andromeda'), ('AV', 'Avalon'), ('AZ', 'Aztec'), ('BW', 'Beltway'), ('BZ', 'Benzene'), ('BR', 'Bloody Ridge'), ('BS', 'Blue Storm'), ('CR', 'Chain Reaction'), ('CB', 'Circuit Breaker'), ('CO', 'Colosseum'), ('CG', 'Cross Game'), ('DP', "Dante's Peak"), ('DE', 'Demian'), ('DT', 'Desertec'), ('DS', 'Destination'), ('ED', 'Eddy'), ('EC', 'Electric Circuit'), ('EM', 'Empire of the Sun'), ('ES', 'Eye of the Storm'), ('FS', 'Fighting Spirit'), ('FO', 'Fortress'), ('GL', 'Gemlong'), ('GR', 'Grandline'), ('GZ', 'Ground Zero'), ('HB', 'Heartbeat'), ('HR', 'Heartbreak Ridge'), ('HU', 'Hunters'), ('IC', 'Icarus'), ('JA', 'Jade'), ('LM', 'La Mancha'), ('LQ', 'Latin Quarter'), ('LO', 'Longinus'), ('LU', 'Luna'), ('MP', 'Match Point'), ('ME', 'Medusa'), ('MI', 'Mist'), ('OT', 'Othello'), ('OS', 'Outsider'), ('OW', 'Overwatch'), ('PF', 'Pathfinder'), ('PR', 'Polaris Rhapsody'), ('PY', 'Python'), ('QB', 'Queensbridge'), ('RE', 'Resonance'), ('RK', 'Roadkill'), ('SR', 'Sniper Ridge'), ('TC', 'Tau Cross'), ('TS', 'Toad Stone'), ('TO', 'Tornado'), ('WC', 'Wind and Cloud')], max_length=3, null=True, verbose_name='Map'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='win', to=settings.AUTH_USER_MODEL),
        ),
    ]
