# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0013_auto_20170607_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_map',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Map'),
        ),
    ]
