# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-26 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='battlenet',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='discord',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='iccup',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='race',
            field=models.CharField(choices=[('Z', 'Zerg'), ('T', 'Terran'), ('P', 'Protoss'), ('R', 'Random')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='user',
            name='shield_battery',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
